output: Main.c Convert_To_24_Bit.c Write_Image_Header.c Read_8_Bit.c Read_Header_Details.c Write_Pixel_Data.c
	gcc -o output  Main.c Convert_To_24_Bit.c Write_Image_Header.c Read_8_Bit.c Read_Header_Details.c Write_Pixel_Data.c	Print_Header_Details.c
clean:
	rm -rf *o output