output: main.c convert.c makeimageh.c read8.c read-s.c write-o.c
	gcc -o output  Main.c Convert_To_24_Bit.c Write_Image_Header.c Read_8_Bit.c Read_Header_details.c Write_Pixel_Data.c	Print_Header_Details.c
clean:
	rm -rf *o output